---
# Install text editor atom

- name : List user with home directory
  shell: ls -1 /home
  register: list_user
  changed_when: false

- name: Install text editor Atom with package manager snap
  snap:
    name: atom
    classic: yes
    state: present

- name: Install Atom module with Atom Package Manager
  shell: "/snap/bin/apm install {{ item[0] }}"
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item[0] }}"
  become: yes
  become_user: "{{ item[1] }}"
  with_nested:
    - "{{ atom_packages }}"
    - "{{ list_user.stdout_lines }}"

- name: Install os packages for atom linter
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ atom_os_packages }}"
