---
# Install Google cloud repos and packages

- name: Add Google cloud repository signing key on Debian
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Google cloud repository on Debian
  apt_repository:
    repo: deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main
    state: present

- name: Install sdk for Google cloud
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - google-cloud-sdk
    - kubectl

- name: Install Helm with package manager snap
  snap:
    name: helm
    classic: yes
    state: present
